# Generated by Django 5.1.4 on 2025-01-14 23:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=25)),
                ('phone', models.CharField(max_length=15)),
                ('lat', models.CharField(max_length=10)),
                ('lng', models.CharField(max_length=10)),
                ('price', models.IntegerField()),
                ('photo', models.URLField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('gender', models.CharField(max_length=25)),
                ('breed', models.CharField(max_length=25)),
                ('dob', models.DateField()),
                ('photo', models.URLField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dog', to='app1.profile')),
            ],
        ),
    ]
