# Generated by Django 5.1.4 on 2025-01-15 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_alter_dog_breed_alter_dog_dob_alter_dog_gender_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dog',
            old_name='customer',
            new_name='owner',
        ),
    ]
